server:
  endpoint: ":3000"

database:
  driver: "sqlite"
  # dsn: ":memory:"
  # Параметр _fk обязателен для включения гарантий СУБД по проверке
  # существования внешних клюей.
  # Параметр _journal_mode=wal включает WAL-режим.
  # Параметр _synchronous=normal включает синхронный режим записи,
  # который гарантирует сохранение данных на диск перед подтверждением транзакции.
  # Параметр _txlock=immediate включает блокировку транзакций сразу после начала,
  # что позволяет избежать блокировок на уровне базы данных.
  dsn: "./sqlite3.db?_fk=1&_journal_mode=wal&_synchronous=normal&_txlock=immediate"

log:
  level: "debug"
  output: "stdout"
  format: "text"
