CREATE TABLE chats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    created_at DATETIME WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME WITH TIME ZONE
);

CREATE INDEX idx_chats_deleted_at ON chats(deleted_at);
